version: "3.8"

services:
  web:
    container_name: syndra
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      # please copy .env.example to .env and update the values
      - .env
    ports:
      - "${WEB_PORT}:80"
    volumes:
      # please create a `deovr` file on root of this project if it doesn't exist
      - ./deovr:/usr/share/nginx/html/deovr
    restart: unless-stopped